-- Step 10: account-scoped AI usage metering, budget limits, and monthly rollups.
create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  operation text not null,
  model text not null,
  provider text not null default 'google-gemini',
  request_id text,
  input_tokens integer,
  output_tokens integer,
  thinking_tokens integer,
  total_tokens integer,
  image_count integer not null default 0,
  estimated_cost_usd numeric(12,6),
  latency_ms integer,
  success boolean not null,
  cache_hit boolean not null default false,
  error_code text,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_events_user_created_idx on public.ai_usage_events(user_id, created_at desc);
create index if not exists ai_usage_events_operation_created_idx on public.ai_usage_events(operation, created_at desc);
create index if not exists ai_usage_events_model_created_idx on public.ai_usage_events(model, created_at desc);
alter table public.ai_usage_events enable row level security;
grant select on public.ai_usage_events to authenticated, service_role;
grant insert, update, delete on public.ai_usage_events to service_role;
revoke insert, update, delete on public.ai_usage_events from authenticated, anon;
drop policy if exists "Users select own AI usage" on public.ai_usage_events;
create policy "Users select own AI usage" on public.ai_usage_events for select to authenticated using ((select auth.uid()) = user_id);

create or replace view public.ai_usage_monthly with (security_invoker = true) as
select user_id, date_trunc('month', created_at) as month,
  count(*) as requests,
  count(*) filter (where success) as successful_requests,
  count(*) filter (where not success) as failed_requests,
  coalesce(sum(input_tokens),0) as input_tokens,
  coalesce(sum(output_tokens),0) as output_tokens,
  coalesce(sum(thinking_tokens),0) as thinking_tokens,
  coalesce(sum(total_tokens),0) as total_tokens,
  coalesce(sum(image_count),0) as image_count,
  coalesce(sum(estimated_cost_usd),0)::numeric(12,6) as estimated_cost_usd,
  coalesce(avg(latency_ms),0)::numeric(12,2) as avg_latency_ms
from public.ai_usage_events
group by user_id, date_trunc('month', created_at);
grant select on public.ai_usage_monthly to authenticated, service_role;

create table if not exists public.ai_usage_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  monthly_budget_usd numeric(12,2),
  daily_request_limit integer,
  monthly_image_limit integer,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.ai_usage_limits enable row level security;
grant select on public.ai_usage_limits to authenticated, service_role;
grant insert, update, delete on public.ai_usage_limits to service_role;
drop policy if exists "Users select own AI limits" on public.ai_usage_limits;
create policy "Users select own AI limits" on public.ai_usage_limits for select to authenticated using ((select auth.uid()) = user_id);

create or replace function public.ensure_default_ai_usage_limits()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.user_id is not null then
    insert into public.ai_usage_limits (user_id, monthly_budget_usd, daily_request_limit, monthly_image_limit, enabled)
    values (new.user_id, 10.00, 100, 100, true)
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists ensure_default_ai_usage_limits_on_profile on public.user_profiles;
create trigger ensure_default_ai_usage_limits_on_profile after insert or update of user_id on public.user_profiles
for each row execute function public.ensure_default_ai_usage_limits();
