create table if not exists public.creative_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  body text not null default '',
  tags text[] not null default '{}',
  status text not null default 'seed' check (status in ('seed','draft','developing','finished')),
  source_prompt text,
  source_dream_id bigint references public.dreams(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists creative_entries_user_updated_idx on public.creative_entries(user_id, updated_at desc);
create index if not exists creative_entries_user_status_idx on public.creative_entries(user_id, status);
create index if not exists creative_entries_tags_gin_idx on public.creative_entries using gin(tags);
alter table public.creative_entries enable row level security;

create table if not exists public.creative_entry_versions (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.creative_entries(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  body text not null default '',
  tags text[] not null default '{}',
  status text not null,
  created_at timestamptz not null default now()
);

create index if not exists creative_entry_versions_entry_created_idx on public.creative_entry_versions(entry_id, created_at desc);
create index if not exists creative_entry_versions_user_idx on public.creative_entry_versions(user_id);
alter table public.creative_entry_versions enable row level security;

revoke all on public.creative_entries from anon, authenticated;
revoke all on public.creative_entry_versions from anon, authenticated;
