-- Persistent entity layer for the personal dream encyclopedia.
-- Canonical entities survive individual mention edits so dormancy and return can be measured later.

alter table public.dreams
  add constraint dreams_id_user_id_unique unique (id, user_id);

create table if not exists public.dream_entities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check (entity_type in ('theme','symbol','character','place','emotion','transformation','object','action')),
  canonical_name text not null,
  normalized_name text not null,
  aliases jsonb not null default '[]'::jsonb check (jsonb_typeof(aliases) = 'array'),
  status text not null default 'active' check (status in ('active','merged')),
  merged_into_entity_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dream_entities_user_type_name_unique unique (user_id, entity_type, normalized_name),
  constraint dream_entities_id_user_unique unique (id, user_id),
  constraint dream_entities_merge_owner_fkey foreign key (merged_into_entity_id, user_id)
    references public.dream_entities(id, user_id),
  constraint dream_entities_merge_state_check check (
    (status = 'active' and merged_into_entity_id is null)
    or (status = 'merged' and merged_into_entity_id is not null and merged_into_entity_id <> id)
  )
);

create table if not exists public.dream_entity_mentions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  dream_id bigint not null,
  entity_id bigint not null,
  surface_form text not null,
  context text,
  confidence text not null default 'medium' check (confidence in ('low','medium','high')),
  source_version integer not null default 1,
  created_at timestamptz not null default now(),
  constraint dream_entity_mentions_dream_entity_unique unique (dream_id, entity_id),
  constraint dream_entity_mentions_dream_owner_fkey foreign key (dream_id, user_id)
    references public.dreams(id, user_id) on delete cascade,
  constraint dream_entity_mentions_entity_owner_fkey foreign key (entity_id, user_id)
    references public.dream_entities(id, user_id) on delete cascade
);

create index if not exists dream_entities_user_type_idx
  on public.dream_entities(user_id, entity_type, status);
create index if not exists dream_entity_mentions_user_entity_idx
  on public.dream_entity_mentions(user_id, entity_id);
create index if not exists dream_entity_mentions_user_dream_idx
  on public.dream_entity_mentions(user_id, dream_id);
create index if not exists dream_entities_merge_owner_idx
  on public.dream_entities(merged_into_entity_id, user_id);
create index if not exists dream_entity_mentions_dream_owner_idx
  on public.dream_entity_mentions(dream_id, user_id);
create index if not exists dream_entity_mentions_entity_owner_idx
  on public.dream_entity_mentions(entity_id, user_id);

drop trigger if exists set_dream_entities_updated_at on public.dream_entities;
create trigger set_dream_entities_updated_at before update on public.dream_entities
for each row execute function public.set_updated_at();

alter table public.dream_entities enable row level security;
alter table public.dream_entity_mentions enable row level security;

grant select, insert, update, delete on table public.dream_entities to authenticated, service_role;
grant select, insert, update, delete on table public.dream_entity_mentions to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

drop policy if exists "Users select own dream entities" on public.dream_entities;
create policy "Users select own dream entities" on public.dream_entities for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own dream entities" on public.dream_entities;
create policy "Users insert own dream entities" on public.dream_entities for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own dream entities" on public.dream_entities;
create policy "Users update own dream entities" on public.dream_entities for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own dream entities" on public.dream_entities;
create policy "Users delete own dream entities" on public.dream_entities for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users select own dream entity mentions" on public.dream_entity_mentions;
create policy "Users select own dream entity mentions" on public.dream_entity_mentions for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "Users insert own dream entity mentions" on public.dream_entity_mentions;
create policy "Users insert own dream entity mentions" on public.dream_entity_mentions for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own dream entity mentions" on public.dream_entity_mentions;
create policy "Users update own dream entity mentions" on public.dream_entity_mentions for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own dream entity mentions" on public.dream_entity_mentions;
create policy "Users delete own dream entity mentions" on public.dream_entity_mentions for delete to authenticated
using ((select auth.uid()) = user_id);


-- Backfill existing analyzed dreams without making any AI calls.
with feature_map(entity_type, feature_key) as (
  values ('theme','themes'), ('symbol','symbols'), ('character','characters'), ('place','locations'),
         ('emotion','emotions'), ('transformation','transformations'), ('object','objects'), ('action','actions')
), extracted as (
  select d.user_id, m.entity_type, value as canonical_name,
    trim(regexp_replace(regexp_replace(lower(value), '[^a-z0-9[:space:]-]', ' ', 'g'), '[[:space:]]+', ' ', 'g')) as normalized_name
  from public.dreams d cross join feature_map m
  cross join lateral jsonb_array_elements_text(coalesce(d.feature_json -> m.feature_key, '[]'::jsonb)) value
  where d.user_id is not null and d.feature_json is not null
)
insert into public.dream_entities(user_id, entity_type, canonical_name, normalized_name)
select distinct user_id, entity_type, canonical_name, normalized_name from extracted where normalized_name <> ''
on conflict do nothing;

with feature_map(entity_type, feature_key) as (
  values ('theme','themes'), ('symbol','symbols'), ('character','characters'), ('place','locations'),
         ('emotion','emotions'), ('transformation','transformations'), ('object','objects'), ('action','actions')
), extracted as (
  select d.id as dream_id, d.user_id, d.feature_version, m.entity_type, value as surface_form,
    trim(regexp_replace(regexp_replace(lower(value), '[^a-z0-9[:space:]-]', ' ', 'g'), '[[:space:]]+', ' ', 'g')) as normalized_name
  from public.dreams d cross join feature_map m
  cross join lateral jsonb_array_elements_text(coalesce(d.feature_json -> m.feature_key, '[]'::jsonb)) value
  where d.user_id is not null and d.feature_json is not null
)
insert into public.dream_entity_mentions(user_id, dream_id, entity_id, surface_form, confidence, source_version)
select x.user_id, x.dream_id, e.id, x.surface_form, 'medium', coalesce(x.feature_version, 1)
from extracted x join public.dream_entities e
  on e.user_id=x.user_id and e.entity_type=x.entity_type and e.normalized_name=x.normalized_name
where x.normalized_name <> ''
on conflict (dream_id, entity_id) do nothing;
