-- Step 8 private-beta schema. Browser roles have no direct access to these
-- coordination tables; trusted server routes mediate invitations and feedback.

create table if not exists public.beta_invites (
  id bigint generated by default as identity primary key,
  email text not null,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);
create unique index if not exists beta_invites_email_unique on public.beta_invites (lower(email));
create index if not exists beta_invites_accepted_by_idx on public.beta_invites (accepted_by);

create table if not exists public.beta_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'general',
  message text not null,
  page text,
  created_at timestamptz not null default now()
);
create index if not exists beta_feedback_user_id_idx on public.beta_feedback (user_id);
create index if not exists beta_feedback_created_at_idx on public.beta_feedback (created_at desc);

alter table public.beta_invites enable row level security;
alter table public.beta_feedback enable row level security;
revoke all on table public.beta_invites from anon, authenticated;
revoke all on table public.beta_feedback from anon, authenticated;
grant select, insert, update, delete on table public.beta_invites to service_role;
grant select, insert, update, delete on table public.beta_feedback to service_role;
grant usage, select on all sequences in schema public to service_role;
