-- AstraDream hosted persistence schema for Supabase/Postgres.
-- Authenticated data is user-owned and protected with RLS. Trusted backend work
-- may still use the server-only service-role key, which must never reach the browser.

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null, dob date not null, tob time not null,
  lob_lat double precision not null, lob_lng double precision not null, lob_name text not null,
  life_path integer, chinese_zodiac text, birth_chart_interpretation text,
  sun_sign text, moon_sign text, mercury_sign text, venus_sign text, mars_sign text,
  jupiter_sign text, saturn_sign text, uranus_sign text, neptune_sign text, pluto_sign text,
  rising_sign text, context_memory jsonb not null default '[]'::jsonb,
  context_memory_version integer not null default 1,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.dreams (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null, content text not null, date date not null, time time not null,
  location_lat double precision not null, location_lng double precision not null, location_name text not null,
  timezone_name text, interpretation text, image_url text, sun_sign text, moon_sign text,
  mercury_sign text, venus_sign text, mars_sign text, jupiter_sign text, saturn_sign text,
  uranus_sign text, neptune_sign text, pluto_sign text, moon_phase text, day_number integer,
  planetary_influences jsonb, tags jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb, analysis_json jsonb, analysis_version integer,
  astrology_json jsonb, astrology_version integer, feature_json jsonb, feature_version integer,
  context_facts jsonb not null default '[]'::jsonb, revisits jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.ai_cache (
  cache_key text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  cache_type text not null, payload jsonb not null, expires_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.legacy_archive_claims (
  id integer primary key check (id = 1),
  token_hash text not null,
  used_at timestamptz,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists user_profiles_user_id_unique on public.user_profiles(user_id) where user_id is not null;
create index if not exists dreams_date_time_idx on public.dreams (date desc, time desc);
create index if not exists dreams_tags_gin_idx on public.dreams using gin (tags);
create index if not exists dreams_user_id_idx on public.dreams(user_id);
create index if not exists ai_cache_user_id_idx on public.ai_cache(user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at before update on public.user_profiles for each row execute function public.set_updated_at();
drop trigger if exists set_dreams_updated_at on public.dreams;
create trigger set_dreams_updated_at before update on public.dreams for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.dreams enable row level security;
alter table public.ai_cache enable row level security;
alter table public.legacy_archive_claims enable row level security;

grant select, insert, update, delete on table public.user_profiles to authenticated, service_role;
grant select, insert, update, delete on table public.dreams to authenticated, service_role;
grant select, insert, update, delete on table public.ai_cache to authenticated, service_role;
revoke all on table public.legacy_archive_claims from anon, authenticated;
grant select, insert, update on table public.legacy_archive_claims to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

-- Legacy pre-auth rows remain user_id = null. They are invisible through these
-- authenticated policies until the one-time trusted claim operation assigns them.
drop policy if exists "Users select own profile" on public.user_profiles;
create policy "Users select own profile" on public.user_profiles for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists "Users insert own profile" on public.user_profiles;
create policy "Users insert own profile" on public.user_profiles for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own profile" on public.user_profiles;
create policy "Users update own profile" on public.user_profiles for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own profile" on public.user_profiles;
create policy "Users delete own profile" on public.user_profiles for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users select own dreams" on public.dreams;
create policy "Users select own dreams" on public.dreams for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists "Users insert own dreams" on public.dreams;
create policy "Users insert own dreams" on public.dreams for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own dreams" on public.dreams;
create policy "Users update own dreams" on public.dreams for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own dreams" on public.dreams;
create policy "Users delete own dreams" on public.dreams for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users select own ai cache" on public.ai_cache;
create policy "Users select own ai cache" on public.ai_cache for select to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
drop policy if exists "Users insert own ai cache" on public.ai_cache;
create policy "Users insert own ai cache" on public.ai_cache for insert to authenticated
with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own ai cache" on public.ai_cache;
create policy "Users update own ai cache" on public.ai_cache for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users delete own ai cache" on public.ai_cache;
create policy "Users delete own ai cache" on public.ai_cache for delete to authenticated
using ((select auth.uid()) = user_id);

-- This RPC is invoked only with the server-only service role. The user's access
-- token is verified separately before the trusted backend supplies p_user_id.
create or replace function public.claim_legacy_archive(p_user_id uuid, p_token_hash text)
returns jsonb language plpgsql set search_path = '' as $$
declare
  claim_row public.legacy_archive_claims%rowtype;
  profile_count integer := 0;
  dream_count integer := 0;
  cache_count integer := 0;
begin
  if not exists (select 1 from auth.users where id = p_user_id) then raise exception 'Authenticated user does not exist'; end if;
  select * into claim_row from public.legacy_archive_claims where id = 1 for update;
  if not found then raise exception 'Legacy archive claim is not configured'; end if;
  if claim_row.used_at is not null then
    if claim_row.user_id = p_user_id then return jsonb_build_object('claimed', true, 'already_claimed', true); end if;
    raise exception 'Legacy archive has already been claimed';
  end if;
  if claim_row.token_hash <> p_token_hash then raise exception 'Invalid archive claim code'; end if;
  if exists (select 1 from public.user_profiles where user_id = p_user_id) then raise exception 'This account already owns a profile'; end if;
  update public.user_profiles set user_id = p_user_id where user_id is null;
  get diagnostics profile_count = row_count;
  if profile_count <> 1 then raise exception 'Expected exactly one unclaimed legacy profile, found %', profile_count; end if;
  update public.dreams set user_id = p_user_id where user_id is null;
  get diagnostics dream_count = row_count;
  update public.ai_cache set user_id = p_user_id where user_id is null;
  get diagnostics cache_count = row_count;
  update public.legacy_archive_claims set used_at = now(), user_id = p_user_id where id = 1;
  return jsonb_build_object('claimed', true, 'already_claimed', false, 'profile_count', profile_count, 'dream_count', dream_count, 'cache_count', cache_count);
end;
$$;
revoke all on function public.claim_legacy_archive(uuid, text) from public, anon, authenticated;
grant execute on function public.claim_legacy_archive(uuid, text) to service_role;

insert into storage.buckets (id, name, public)
values ('dream-images', 'dream-images', true)
on conflict (id) do update set public = excluded.public;

-- Transitional only. Private user-owned image paths are the next storage cutover.
drop policy if exists "Public dream image reads" on storage.objects;
create policy "Public dream image reads" on storage.objects for select to anon, authenticated
using (bucket_id = 'dream-images');
