-- AstraDream hosted persistence schema for Supabase/Postgres.
-- Phase 1 remains single-user. Direct browser reads/writes are denied;
-- the application server accesses these tables with a server-only service-role key.

create table if not exists public.user_profiles (
  id bigint primary key check (id = 1),
  name text not null,
  dob date not null,
  tob time not null,
  lob_lat double precision not null,
  lob_lng double precision not null,
  lob_name text not null,
  life_path integer,
  chinese_zodiac text,
  birth_chart_interpretation text,
  sun_sign text,
  moon_sign text,
  mercury_sign text,
  venus_sign text,
  mars_sign text,
  jupiter_sign text,
  saturn_sign text,
  uranus_sign text,
  neptune_sign text,
  pluto_sign text,
  rising_sign text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dreams (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  date date not null,
  time time not null,
  location_lat double precision not null,
  location_lng double precision not null,
  location_name text not null,
  interpretation text,
  image_url text,
  sun_sign text,
  moon_sign text,
  mercury_sign text,
  venus_sign text,
  mars_sign text,
  jupiter_sign text,
  saturn_sign text,
  uranus_sign text,
  neptune_sign text,
  pluto_sign text,
  moon_phase text,
  day_number integer,
  planetary_influences jsonb,
  tags jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dreams_date_time_idx on public.dreams (date desc, time desc);
create index if not exists dreams_tags_gin_idx on public.dreams using gin (tags);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_dreams_updated_at on public.dreams;
create trigger set_dreams_updated_at before update on public.dreams
for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.dreams enable row level security;

grant select, insert, update, delete on table public.user_profiles to service_role;
grant select, insert, update, delete on table public.dreams to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public)
values ('dream-images', 'dream-images', true)
on conflict (id) do update set public = excluded.public;

-- Generated dream images are intentionally public because the app displays their URLs.
-- Upload/update/delete operations remain server-only via the service-role key.
drop policy if exists "Public dream image reads" on storage.objects;
create policy "Public dream image reads"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'dream-images');
